# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quetion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=4096)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='quetion',
            name='tags',
            field=models.ManyToManyField(to='ask_app.Tag'),
        ),
    ]
