# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0002_auto_20160426_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quetion',
            old_name='answer_user',
            new_name='question_user',
        ),
    ]
