# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0008_auto_20160426_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ask_app.Quetion'),
        ),
    ]
