# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0009_auto_20160426_1256'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quetion',
            managers=[
            ],
        ),
    ]
