# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0010_auto_20160426_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='quetion',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
